[project]
name = "eurosat-classifier"
version = "0.1.0"
requires-python = ">=3.12"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
dev = ["black", "pre-commit"]

[tool.black]
line-length = 88
target-version = ["py312"]
