name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Black check
        run: |
          black --check . || true
      - name: Run tests
        run: pytest --cov=eurosat --cov-report=xml --cov-fail-under=0
      - name: Upload coverage
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
