name: Test & Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint with black
        run: black --check eurosat tests
      - name: Run Tests
        run: pytest --disable-warnings
